_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

index:
    path:     /login
    defaults: { _controller: AcmeDemoBundle:Login:index }

addteacher:
    path:     /addteacher
    defaults: { _controller: AcmeDemoBundle:AddTeacher:addteacher }

addstudent:
    path:     /addstudent
    defaults: { _controller: AcmeDemoBundle:AddStudent:addstudent }
